version: "3.8"

services:
  - type: web
    name: news-collector
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    networks:
      - app-network
    envVars:
      - key: NODE_ENV
        value: production

networks:
  app-network:
    driver: bridge
